### ISSUE TITLE
Bioconda package is broken

### ISSUE THREAD

**Issue by MattBashton** [AstraZeneca-NGS/disambiguate#11]
Hi I've installed the bioconda version of `ngs_disambiguate` however it's dependencies appear to be borked: 

`ngs_disambiguate 
ngs_disambiguate: error while loading shared libraries: libbamtools.so.2.4.0: cannot open shared object file: No such file or directory`

**Comment by chapmanb** [comment]
Matt;
Sorry about the issue, I believe this is due to bioconda updating to use bamtools 2.4.1. There was a rebuilt ngs-disambiguate package but due to version naming we were still getting the older one: we named the original by the date (2016.11.08) and the fixed version was 1.0.0 which resolved after the date based one so didn't get installed. I re-built this with a fixed date based naming scheme and pinned against the right bamtools so if you do:
```
conda install -c conda-forge -c bioconda ngs-disambiguate
```
you should get the fixed version which I hope will work cleanly for you. Thanks again for the report.

**Comment by MattBashton** [comment]
Thanks for the fix, I compiled from source in the end using bamtools 2.4.0, assumed something had gone wrong on the packaging front, so glad the package is now working again.
